export enum CategoryConstraints{

    CATEGORY_NAME_MAXVALUE=50,
    CATEGORY_NAME_MAXLENGTH="Max supported length of category name is 50",

    MAX_PRODUCTS_PER_CATEGORY_VALUE=20
    /*
    
    PRICE_MAXVALUE=10000000,
    PRICE_MAXLENGTH="MAX SUPPORTED LENGTH OF PRODUCT PRICE IS 1 CRORE",

    BRAND_MAXVALUE=50,
    BRAND_MAXLENGTH="MAX SUPPORTED BRAND VALUE LENGTH IS 50",
    
    */


}